#!/bin/sh

git submodule update --init

# requirements:
# python
# ruby

# create a virtual environment
python3 -m venv unicorn-venv

# activate the venv
source unicorn-venv/bin/activate

# install Herd requirements
pip install -r tools/Herd/requirements.txt

# install Ruby requirements
cd tools/cfn-checker
gem install bundler
bundle install --path ./
cd ${OLDPWD}

# to update submodules
git submodule foreach git pull origin master
cd tools/Unicorn-Wiz

# server will run wizard, then it'll generate configs and exit
pwd
python3 server.py
cd ${OLDPWD}

# at this point we have cfn templates in child, predeploy & stack + herd.*.yaml
# run cfn-checker on all template files

# if cfn-checker fails, abourt
# else, run herd to deploy the script

deactivate
# destroy the virutalenv
deactivate
rm -rf unicorn-venv
