format: key-value
params:
    DevAwsAccountId: 
    ProdAwsAccountId: 
    appName: 
    BuildImageName: aws/codebuild/standard:2.0
    QSS3BucketName: 
    QSS3KeyPrefix:  herd/test1
    QSS3BucketRegion: 
    ProdChildAccountRoleName: pipeline-prod-role
    DevChildAccountRoleName: pipeline-dev-role
    StagingBucket: 
    FuzzerDeployKey: herd/test1/deployment.zip
